/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica18.main_window;

/**
 * This class is about a Window for a Specified Book.
 * @version 1.0
 * @author Alberto J. Marun I.
 * @date April 2021.
 */
public class BookInformationWindow extends javax.swing.JFrame {
    private final MainWindow parent_window;
    
    /**
     * Constructor of the BookInformationWindow to show the selected book
     * @param parent (MainWindow) Parent JFrame where comes this window.
     */
    public BookInformationWindow(MainWindow parent) {
        initComponents();
        this.parent_window = parent;
        setBookInformation();
    }
    
    /**
     * Set the labels with the information of the selected book.
     */
    public final void setBookInformation(){
        book_title.setText(parent_window.toArray()[0]);
        label_book_author.setText(parent_window.toArray()[1]);
        label_book_editorial.setText(parent_window.toArray()[2]);
        label_book_age.setText(parent_window.toArray()[3]);
        label_book_genres.setText(parent_window.toArray()[4]);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        book_title = new javax.swing.JLabel();
        book_information = new javax.swing.JPanel();
        label_author = new javax.swing.JLabel();
        label_book_author = new javax.swing.JLabel();
        label_editorial = new javax.swing.JLabel();
        label_book_editorial = new javax.swing.JLabel();
        label_ages = new javax.swing.JLabel();
        label_book_age = new javax.swing.JLabel();
        label_genres = new javax.swing.JLabel();
        label_book_genres = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Información del Libro");
        setMaximumSize(new java.awt.Dimension(1300, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        book_title.setBackground(new java.awt.Color(153, 204, 255));
        book_title.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        book_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        book_title.setText("Book_Title");
        book_title.setToolTipText("");
        book_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(book_title, java.awt.BorderLayout.NORTH);

        book_information.setLayout(new java.awt.GridLayout(4, 2));

        label_author.setFont(new java.awt.Font(".SF NS Text", 3, 14)); // NOI18N
        label_author.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_author.setText("Autor:");
        book_information.add(label_author);

        label_book_author.setFont(new java.awt.Font(".SF NS Text", 2, 16)); // NOI18N
        label_book_author.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_book_author.setText("Book_Author");
        book_information.add(label_book_author);

        label_editorial.setFont(new java.awt.Font(".SF NS Text", 3, 14)); // NOI18N
        label_editorial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_editorial.setText("Editorial:");
        book_information.add(label_editorial);

        label_book_editorial.setFont(new java.awt.Font(".SF NS Text", 2, 16)); // NOI18N
        label_book_editorial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_book_editorial.setText("Editorial");
        book_information.add(label_book_editorial);

        label_ages.setFont(new java.awt.Font(".SF NS Text", 3, 14)); // NOI18N
        label_ages.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_ages.setText("Edad:");
        book_information.add(label_ages);

        label_book_age.setFont(new java.awt.Font(".SF NS Text", 2, 16)); // NOI18N
        label_book_age.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_book_age.setText("Book_Age");
        book_information.add(label_book_age);

        label_genres.setFont(new java.awt.Font(".SF NS Text", 3, 14)); // NOI18N
        label_genres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_genres.setText("Géneros:");
        book_information.add(label_genres);

        label_book_genres.setFont(new java.awt.Font(".SF NS Text", 2, 16)); // NOI18N
        label_book_genres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_book_genres.setText("Book_Age");
        book_information.add(label_book_genres);

        getContentPane().add(book_information, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel book_information;
    private javax.swing.JLabel book_title;
    private javax.swing.JLabel label_ages;
    private javax.swing.JLabel label_author;
    private javax.swing.JLabel label_book_age;
    private javax.swing.JLabel label_book_author;
    private javax.swing.JLabel label_book_editorial;
    private javax.swing.JLabel label_book_genres;
    private javax.swing.JLabel label_editorial;
    private javax.swing.JLabel label_genres;
    // End of variables declaration//GEN-END:variables
}
