package MainWindow;


import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DAW_16_AlbertoMarun
 */
public class MainWindows extends javax.swing.JFrame {
    
    private int count;
    /**
     * Creates new form MainWindows
     */
    public MainWindows() {
        initComponents();
        count = 0;
        
        String[] item = {"Alberto", "Marun"};
        
        DefaultTableModel model = (DefaultTableModel) people.getModel();
        model.addColumn("Apellidos");
        model.addRow(item);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        counterLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkBoxOption1 = new javax.swing.JCheckBox();
        checkBoxOption2 = new javax.swing.JCheckBox();
        checkBoxOption3 = new javax.swing.JCheckBox();
        radioButtonA = new javax.swing.JRadioButton();
        radioButtonB = new javax.swing.JRadioButton();
        radioButtonC = new javax.swing.JRadioButton();
        submit = new javax.swing.JButton();
        animalSelected = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        people = new javax.swing.JTable();
        nameInput = new javax.swing.JTextField();
        addPerson = new javax.swing.JButton();
        surnameInput = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Substract");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substract(evt);
            }
        });

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addition(evt);
            }
        });

        counterLabel.setText("0");

        jLabel2.setText("Contador:");

        checkBoxOption1.setText("Opcion 1");
        checkBoxOption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxOption1ActionPerformed(evt);
            }
        });

        checkBoxOption2.setText("Opcion 2");

        checkBoxOption3.setText("jCheckBox3");

        buttonGroup1.add(radioButtonA);
        radioButtonA.setText("Opcion A");
        radioButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonAActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioButtonB);
        radioButtonB.setText("Opcion B");

        buttonGroup1.add(radioButtonC);
        radioButtonC.setText("Opcion C");

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        animalSelected.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perro", "Gato", "Loro", "Oso", "Panda" }));

        people.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane1.setViewportView(people);

        addPerson.setText("Add");
        addPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 395, Short.MAX_VALUE)
                        .addComponent(counterLabel)
                        .addGap(369, 369, 369))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(52, 52, 52))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkBoxOption3)
                                    .addComponent(checkBoxOption2)
                                    .addComponent(checkBoxOption1))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioButtonB)
                                    .addComponent(radioButtonC)
                                    .addComponent(radioButtonA))
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(animalSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addPerson)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(deleteButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(submit)
                                        .addGap(56, 56, 56)))
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(surnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(92, 92, 92))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(counterLabel)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxOption1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radioButtonA, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkBoxOption2)
                            .addComponent(radioButtonB))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkBoxOption3)
                            .addComponent(radioButtonC))
                        .addGap(18, 18, 18)
                        .addComponent(submit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(surnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteButton)
                            .addComponent(addPerson))
                        .addGap(85, 85, 85)
                        .addComponent(animalSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void substract(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_substract
        count--;
        counterLabel.setText(Integer.toString(count));
    }//GEN-LAST:event_substract

    private void addition(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addition
        count++;
        counterLabel.setText(Integer.toString(count));
    }//GEN-LAST:event_addition

    private void radioButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonAActionPerformed

    private void checkBoxOption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxOption1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxOption1ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        System.out.println("La opcion Escogida es: " + getSelectedRadioButton());
        
        for(String selected : getCheckBox()){
            System.out.println(selected);
        }
        
        System.out.println("Has seleccionado " + animalSelected.getSelectedItem());
    }//GEN-LAST:event_submitActionPerformed

    private void addPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) people.getModel();
        
        String[] person = {nameInput.getText(), surnameInput.getText()};
        model.addRow(person);
        
    }//GEN-LAST:event_addPersonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int index = people.getSelectedRow();
        
        if (people.getSelectedRow() != -1){
            DefaultTableModel model = (DefaultTableModel) people.getModel();
            model.removeRow(people.getSelectedRow());
        } else {
            System.out.println("No ha seleccionado ningun usuario");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private String getSelectedRadioButton(){
        String selected = "";
        
        if(radioButtonA.isSelected()){
            selected = "Opcion A";
        } else if(radioButtonB.isSelected()){
            selected = "Opcion B";
        } else if(radioButtonC.isSelected()){
            selected = "Opcion C";
        }
        
        return selected;
    }
    
    private ArrayList<String> getCheckBox(){
        ArrayList<String> selected = new ArrayList<>();
        
        if(checkBoxOption1.isSelected()){
            selected.add("Opcion 1");
        }
        
        if(checkBoxOption2.isSelected()){
            selected.add("Opcion 2");
        }
        
        if(checkBoxOption3.isSelected()){
            selected.add("Opcion 3");
        }
        
        return selected;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindows().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPerson;
    private javax.swing.JComboBox<String> animalSelected;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkBoxOption1;
    private javax.swing.JCheckBox checkBoxOption2;
    private javax.swing.JCheckBox checkBoxOption3;
    private javax.swing.JLabel counterLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameInput;
    private javax.swing.JTable people;
    private javax.swing.JRadioButton radioButtonA;
    private javax.swing.JRadioButton radioButtonB;
    private javax.swing.JRadioButton radioButtonC;
    private javax.swing.JButton submit;
    private javax.swing.JTextField surnameInput;
    // End of variables declaration//GEN-END:variables
}
